# Generated by Django 4.1.7 on 2023-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=150, verbose_name='Line 1')),
                ('line_2', models.CharField(max_length=150, verbose_name='Line 2')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('state', models.CharField(max_length=80, verbose_name='State')),
                ('country', models.CharField(max_length=80, verbose_name='Country')),
                ('latitude', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
