# Generated by Django 4.1.7 on 2023-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_attraction_minimum_age'),
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='attractions',
            field=models.ManyToManyField(to='attractions.attraction', verbose_name='Attractions'),
        ),
    ]
