# Generated by Django 4.1.7 on 2023-02-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('sights', '0002_sight_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='comments',
            field=models.ManyToManyField(to='comments.comment', verbose_name='Comments'),
        ),
    ]
