# Generated by Django 4.1.7 on 2023-02-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('sights', '0003_sight_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='reveiews',
            field=models.ManyToManyField(to='reviews.review', verbose_name='Review'),
        ),
    ]
