# Generated by Django 4.1.7 on 2023-02-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('sights', '0004_sight_reveiews'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.adress', verbose_name='Review'),
        ),
    ]
