# Generated by Django 4.1.7 on 2023-02-21 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('sights', '0005_sight_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.adress', verbose_name='Review'),
        ),
    ]
