# Generated by Django 4.1.7 on 2023-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_alter_sight_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sights'),
        ),
    ]
