# Generated by Django 4.1.7 on 2023-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0007_sight_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sights', verbose_name='Image'),
        ),
    ]
