# Generated by Django 4.1.7 on 2023-03-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
        ('sights', '0009_rename_reveiews_sight_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adresses.adress', verbose_name='Adress'),
        ),
    ]
