# Generated by Django 4.1.7 on 2023-03-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0010_alter_sight_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOfIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='sight',
            name='document_of_intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sights.documentofintent', verbose_name='Document of intent'),
        ),
    ]
