# Generated by Django 4.1.7 on 2023-02-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='minimum_age',
            field=models.IntegerField(default=10, verbose_name='Minimum age'),
        ),
    ]
